### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by deklanw** [muhanzhang/IGMC#10]
1) One advantage of a node-embedding-based link predictor is that it's relatively easy to define item-to-item or user-to-user similarity from the embeddings (for recommender systems). Since your approach doesn't use node embeddings, is there any analogous way of defining similarity between nodes within one of the parts?

2) Have you tried loss functions and evaluations for ranking and implicit feedback instead of rating prediction and explicit feedback?

**Comment by muhanzhang** [comment]
Hi! For the first question: IGMC does not learn node embeddings so that we can compute distance easily between node embeddings to predict links. Instead, IGMC learns an embedding for each link of interest (from its enclosing subgraph). It can be regarded as a generalization of the inner product kernel between node embeddings (like in MF) to a kernel between two nodes defined on their enclosing subgraphs realized by a GNN. This makes retrieval of top-K similar users/items not as cheap as embedding-based approaches, as we need to extract an enclosing subgraph and apply the GNN for every (target user, user) pairs. There are ways to alleviate it, including multi-stage ranking (first use simple heuristics to filter out most irrelevant users and then apply IGMC). But it is still a key challenge for scaling IGMC to super-large datasets, and needs the community to find a solution.

For the second problem: No, I haven't. But I remember there are several papers citing IGMC which extend it to ranking metrics.

**Comment by deklanw** [comment]
Hi, thanks for the quick reply

> This makes retrieval of top-K similar users/items not as cheap as embedding-based approaches, as we need to extract an enclosing subgraph and apply the GNN for every (target user, user) pairs.

IGMC is always trained with the subgraph of one-hop from a (user, item) pair though, right? Isn't one-hop from a (user, user) pair a totally different kind of subgraph (would only contain the 2 users and then all the items they interact with)? How does it apply in this case? Sorry if I'm missing something obvious

>But I remember there are several papers citing IGMC which extend it to ranking metrics. 

Would it happen to be "Bipartite Graph Embedding via Mutual Information Maximization"? https://arxiv.org/abs/2012.05442 I found performance comparisons in here but I'm wondering if you had another in mind

**Comment by muhanzhang** [comment]
For the first one, yeah, IGMC only applies to (user, item) pairs. I was using user/item exchangably. What I meant is that from a user to retrieve top K items require extracting a subgraph around each (target user, item) pair. If we can supervise on (user, user) pairs, we can also apply IGMC to learn a user-user kernel.

For the second one, yes, "Bipartite Graph Embedding via Mutual Information Maximization" is one paper. Another one I know is "Inductive Relational Matrix Completion", https://arxiv.org/pdf/2007.04833.pdf

**Comment by deklanw** [comment]
Makes sense. Thanks for your help!
