### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by technophyte** [muhanzhang/IGMC#27]
Hi,
I've used 'visualize' option to view the subgraphs and predicted ratings. I wanted to know how to get the user and item ids corresponding to the 'red' and 'blue' nodes in the visualization.pdf so that it can be identified which target user-item pair this enclosing subgraph has been built around. 

I am using this code for a new dataset, and I want to annotate the nodes in the visualization with the actual row and column indices so that the rating matrix can be tallied with the corresponding subgraph. Thanks.

**Comment by muhanzhang** [comment]
It's not directly supported and needs some work. Because the original node indices have been removed when constructing the local enclosing subgraphs, there are no node indices recorded in each PyG data object. You may need to modify this [function](https://github.com/muhanzhang/IGMC/blob/5fa0e3cb1bdc46ffcb97fa6e0249a553e2e0b438/util_functions.py#L208) (and the following functions that call it) to record the `ind[0]` and `ind[1]`, then you can visualize them.

**Comment by technophyte** [comment]
Thanks for your reply. It helped!
