### ISSUE TITLE
[Feature Request] Add `requirements.txt`

### ISSUE THREAD

**Issue by SauravMaheshkar** [muhanzhang/IGMC#29]
The repository as of now lacks a `requirements.txt`. It'd be nice to have the explicit PyTorch Geometric version in order to run the experiments. Hopefully, this will prevents errors like #7 from taking place.

Having a `requirements.txt` file would make reproducibility and the onboarding process much easier.

**Comment by muhanzhang** [comment]
Hi! I did not include a `requirements.txt` because [PyTorch Geometric installation](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) requires specifying cuda versions. Thus, I still recommend installing pytorch and pyg following the official guides. To avoid #7, one can also directly use the [latest branch](https://github.com/muhanzhang/IGMC/tree/latest). I did not make the latest branch default because there are some performance drops using the latest version.

**Comment by SauravMaheshkar** [comment]
Thanks for the prompt response, that makes sense. Although there is a workaround that I can think of.

```bash
# install_deps.sh
TORCH=$1
CUDA=$2
pip install torch==${TORCH}
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-geometric
```
And then one can install dependencies using the following command
```bash
> sh install_deps.sh 1.8.0 cu102
```
