### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'RGCNConv' object has no attribute 'att'

### ISSUE THREAD

**Issue by lukhofai** [muhanzhang/IGMC#7]
Hi there, 

Very interesting paper. However, When I train it, it shows ' 'RGCNConv' object has no attribute 'att'', When I look at the documentation in pytorch, there is no such attribute as well. Please check it, cheers.

Regards

**Comment by lukhofai** [comment]
Sorry, I believe that was a problem with pytorch geometric version's problem.

**Comment by srvrc** [comment]
I had the same problem with pytorch geometric version 1.6.1. It can be fixed with the following change:

In train_eval.py,  line 170-171

```
gconv.att,
gconv.basis.view(gconv.num_bases, -1)
```
to
```
gconv.comp,
gconv.weight.view(gconv.num_bases, -1)
```

Source: docs of versions 1.4.1 and the latest (1.6.1)

https://pytorch-geometric.readthedocs.io/en/1.4.1/_modules/torch_geometric/nn/conv/rgcn_conv.html
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/rgcn_conv.html#RGCNConv
